"""
Pre-computed reference swing sequences for DTW alignment.

Each reference swing is a dense sequence of pose feature vectors
generated by linearly interpolating between the 8 canonical phase
angle sets in pro_reference.json, then converting angles to normalized
keypoint positions via the pose synthesizer.

Why synthetic references (not real video)?
  We don't have labeled pro video frames. However, the pose synthesizer
  produces biomechanically plausible positions that capture the essential
  SHAPE of the swing trajectory in the feature space. DTW alignment is
  robust to global scale/offset differences because both the user features
  and the reference features are normalized the same way (hip-centered,
  torso-scaled). The relative motion patterns — rising wrists in backswing,
  dropping wrists in downswing — are preserved.

Reference frame budget per phase:
  Address:        5 frames   (stable pre-swing)
  Takeaway:       5 frames
  Backswing:      7 frames   (longest motion arc)
  Top of Swing:   4 frames   (brief peak)
  Downswing:      6 frames   (aggressive, fast)
  Impact:         3 frames   (instantaneous event)
  Follow Through: 7 frames
  Finish:         5 frames   (stable post-swing)
  TOTAL:         42 frames
"""
from __future__ import annotations
import logging
from functools import lru_cache
from typing import Dict, List, Optional, Tuple

import numpy as np

from services.pose_features import extract_features, FEATURE_DIM
from services.pose_synthesizer import synthesize_keypoints

log = logging.getLogger(__name__)

PHASE_NAMES = [
    "Address", "Takeaway", "Backswing", "Top of Swing",
    "Downswing", "Impact", "Follow Through", "Finish",
]

# Frames per phase — chosen to reflect relative swing timing
PHASE_FRAMES: Dict[str, int] = {
    "Address":        5,
    "Takeaway":       5,
    "Backswing":      7,
    "Top of Swing":   4,
    "Downswing":      6,
    "Impact":         3,
    "Follow Through": 7,
    "Finish":         5,
}

TOTAL_REF_FRAMES = sum(PHASE_FRAMES.values())   # 42


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def _lerp(a: Dict, b: Dict, t: float) -> Dict:
    """Linear interpolation between two angle dicts at parameter t ∈ [0,1]."""
    result = {}
    for k, av in a.items():
        bv = b.get(k, av)
        if isinstance(av, (int, float)):
            result[k] = av + t * (bv - av)
        else:
            result[k] = av
    return result


def _angles_to_feature(angles: Dict) -> np.ndarray:
    """Synthesize keypoints from angles and extract DTW feature vector."""
    kps = synthesize_keypoints(
        spine_angle=       float(angles.get("spine_angle",        32)),
        hip_rotation=      float(angles.get("hip_rotation",        0)),
        shoulder_rotation= float(angles.get("shoulder_rotation",   0)),
        left_elbow_angle=  float(angles.get("left_elbow_angle",  160)),
        right_elbow_angle= float(angles.get("right_elbow_angle", 155)),
        weight_distribution=float(angles.get("weight_distribution", 0.5)),
    )
    feat = extract_features(kps, handedness="right")
    if feat is None:
        return np.zeros(FEATURE_DIM, dtype=np.float32)
    return feat


def generate_reference(pro_id: str) -> Optional[Tuple[np.ndarray, List[str]]]:
    """
    Build (features, labels) for a pro reference swing.

    features: (TOTAL_REF_FRAMES, FEATURE_DIM) float32
    labels:   list of TOTAL_REF_FRAMES phase name strings
    """
    try:
        from services.pro_comparison import _load_all_pros
        all_pros = _load_all_pros()
    except Exception as exc:
        log.error("Cannot load pro reference data: %s", exc)
        return None

    pro = all_pros.get(pro_id)
    if not pro:
        log.warning("Pro '%s' not found in reference catalog.", pro_id)
        return None

    phase_data = pro["phases"]
    features: List[np.ndarray] = []
    labels:   List[str]        = []

    for pi, phase_name in enumerate(PHASE_NAMES):
        curr      = phase_data.get(phase_name)
        next_name = PHASE_NAMES[pi + 1] if pi < len(PHASE_NAMES) - 1 else phase_name
        nxt       = phase_data.get(next_name, curr)
        n_frames  = PHASE_FRAMES[phase_name]

        if curr is None:
            log.warning("Phase '%s' missing from pro '%s' — using zeros.", phase_name, pro_id)
            for _ in range(n_frames):
                features.append(np.zeros(FEATURE_DIM, dtype=np.float32))
                labels.append(phase_name)
            continue

        for k in range(n_frames):
            # t=0 at phase start, t=1 at phase end (transitions into next phase)
            t      = k / n_frames
            angles = _lerp(curr, nxt, t)
            feat   = _angles_to_feature(angles)
            features.append(feat)
            labels.append(phase_name)

    return np.stack(features), labels


@lru_cache(maxsize=8)
def get_reference(pro_id: str) -> Optional[Tuple[np.ndarray, List[str]]]:
    """Cached reference for a given pro. Generated once per process lifetime."""
    result = generate_reference(pro_id)
    if result is not None:
        log.info("Reference sequence for '%s': %d frames", pro_id, len(result[1]))
    return result


def preload_all_references() -> None:
    """Call at startup to warm the cache (avoids first-request latency)."""
    try:
        from services.pro_comparison import _load_all_pros
        for pro_id in _load_all_pros().keys():
            get_reference(pro_id)
    except Exception as exc:
        log.warning("Could not preload reference sequences: %s", exc)
