"""
GET /api/pro/{pro_id}
Returns pro catalog data plus synthetic keypoints per phase.
Used by the Compare tab to render the expected pro pose.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException

from services.pose_synthesizer import synthesize_keypoints
from services.pro_comparison import _load_all_pros, load_pro_catalog

router = APIRouter()


@router.get("/pros")
async def list_pros():
    """Pro catalog for the upload-page dropdown."""
    return load_pro_catalog()


@router.get("/pro/{pro_id}")
async def get_pro(pro_id: str):
    """
    Full pro data for the Compare tab.
    Each phase includes angle reference values AND synthetic keypoints
    generated by the forward-kinematics pose synthesizer.
    """
    all_pros = _load_all_pros()
    pro      = all_pros.get(pro_id)
    if not pro:
        raise HTTPException(status_code=404, detail=f"Pro '{pro_id}' not found.")

    phases_with_keypoints = {}
    for phase_name, phase_data in pro["phases"].items():
        kps = synthesize_keypoints(
            spine_angle=        phase_data.get("spine_angle",        32),
            hip_rotation=       phase_data.get("hip_rotation",        0),
            shoulder_rotation=  phase_data.get("shoulder_rotation",   0),
            left_elbow_angle=   phase_data.get("left_elbow_angle",  160),
            right_elbow_angle=  phase_data.get("right_elbow_angle", 155),
            weight_distribution=phase_data.get("weight_distribution", 0.5),
        )
        phases_with_keypoints[phase_name] = {
            **phase_data,
            "synthetic_keypoints": kps,
        }

    return {
        "id":     pro_id,
        "name":   pro["name"],
        "bio":    pro["bio"],
        "style":  pro["style"],
        "phases": phases_with_keypoints,
    }
